// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAkfKP04ii3cIOQnpwiMxKWi0JpWT9Q4',
    appId: '1:555934920114:web:6c0856d3285832e61bc8ab',
    messagingSenderId: '555934920114',
    projectId: 'gymaplicativo',
    authDomain: 'gymaplicativo.firebaseapp.com',
    storageBucket: 'gymaplicativo.firebasestorage.app',
    measurementId: 'G-39D4J91N4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0shTqa-yYNXbTRblj8LwjewfSFu5OYU',
    appId: '1:555934920114:android:d249c64d8ba35b0d1bc8ab',
    messagingSenderId: '555934920114',
    projectId: 'gymaplicativo',
    storageBucket: 'gymaplicativo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN_Mb6Ls1vyJv3BvIOhrFTNcDY8pn3vMw',
    appId: '1:555934920114:ios:405399acbd214c2a1bc8ab',
    messagingSenderId: '555934920114',
    projectId: 'gymaplicativo',
    storageBucket: 'gymaplicativo.firebasestorage.app',
    iosBundleId: 'com.example.flutterGymAplicativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN_Mb6Ls1vyJv3BvIOhrFTNcDY8pn3vMw',
    appId: '1:555934920114:ios:405399acbd214c2a1bc8ab',
    messagingSenderId: '555934920114',
    projectId: 'gymaplicativo',
    storageBucket: 'gymaplicativo.firebasestorage.app',
    iosBundleId: 'com.example.flutterGymAplicativo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBAkfKP04ii3cIOQnpwiMxKWi0JpWT9Q4',
    appId: '1:555934920114:web:4ad53b8d2b74e62c1bc8ab',
    messagingSenderId: '555934920114',
    projectId: 'gymaplicativo',
    authDomain: 'gymaplicativo.firebaseapp.com',
    storageBucket: 'gymaplicativo.firebasestorage.app',
    measurementId: 'G-ZH11ZP8TMQ',
  );
}
